### ISSUE TITLE
RAML 1.0 does not support repeatable keys

### ISSUE THREAD

**Issue by sichvoge** [raml-apis/MediaWiki#1]
The example starting with [line 102](https://github.com/raml-apis/MediaWiki/blob/master/api.raml#L102) is not correct as RAML does not support any repeatable keys. So there should be only one possible `get`.

**Comment by nogates** [comment]
Thanks for opening this issue @sichvoge. 

Question related to this. What would it happen if instead of using an object to describe the methods, the resource defines an array? Like this:

``` yaml
/:
 - get: 
    200: 
      # rest of the first response
 - get: 
    200: 
      # rest of the second response
```

In this case, yaml would build an array of methods and the keys wouldn't be overridden. Still, I think this is not correct because using an array would mean that the `resource` object can't have no properties, only methods.
